version: '3.8'

services:
  # MySQL 컨테이너 정의
  mysqldb: 
    container_name: mysqldb
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - db.env
    volumes:
      - ./backup:/var/lib/mysql


  # FastAPI 애플리케이션 컨테이너 정의
  fastapi:
    build:
      context: .
      target: final  # Dockerfile에서 최종 레이어를 사용
    restart: always
    environment:
      - MYSQLCLIENT_CFLAGS="-I/usr/include/mysql"
      - MYSQLCLIENT_LDFLAGS="-L/usr/lib/x86_64-linux-gnu -lmysqlclient"
    depends_on:
      - mysqldb  # FastAPI가 MySQL에 의존
    links:
      - mysqldb
    ports:
      - "8000:8000"